apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kk-payments-alerts
  namespace: monitoring 
  labels:
    release: prometheus 
spec:
  groups:
  - name: kk-payments.rules
    rules:
    - alert: KkPaymentsCrashLooping
      expr: increase(kube_pod_container_status_restarts_total{pod=~"kk-payments-.*"}[15m]) > 2
      for: 2m 
      labels:
        severity: critical
        team: lemonsthedev
      annotations:
        summary: "High Pod Restarts detected for {{ $labels.pod }}"
        description: "The pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has restarted multiple times recently. Check the pod logs for a potential CrashLoopBackOff or fatal Node.js error."