apiVersion: apps/v1
kind: Deployment
metadata:
  name: kk-payments
  annotations:
    kubernetes.io/change-cause: "Rolling update to a refined version 1.1.0"
  labels:
    app: kk-payments
    week: "8"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kk-payments
  template:
    metadata:
      labels:
        app: kk-payments
        version: "1.1.1"
    spec:
      imagePullSecrets:
      - name: kijani-registry-credentials
      containers:
      - name: kk-payments

        ##image: solomondocker10277/kk-payments:1.1.0
        image: solomondocker10277/kk-payments-cloud:1.1.2
        ##image: solomondocker10277/kk-payments-cloud:1.1.1  

        readinessProbe:
          httpGet:
            path: /api/health
            port: 8067
          initialDelaySeconds: 5   
          periodSeconds: 10       
          failureThreshold: 3       
          successThreshold: 1
          
        livenessProbe:
          httpGet:
            path: api/health
            port: 8067
          initialDelaySeconds: 15   
          periodSeconds: 20
          failureThreshold: 3
        ports:
        - containerPort: 8067
        envFrom:
        - configMapRef:
            name: kk-payments-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
