---
- name: Deploy kk-payments to EKS cluster
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    env: "staging"
    docker_user: "{{ lookup('env', 'DOCKER_HUB_USER') }}"
    docker_password: "{{ lookup('env', 'DOCKER_HUB_PASSWORD') }}"
    docker_email: "{{ lookup('env', 'DOCKER_HUB_EMAIL') }}"

    fetched_bucket_name: "{{ lookup('pipe', 'cd ../terraform && terraform output -raw receipts_bucket_name') }}"

  tasks:
    - name: 1. Ensure the target environment namespace exists
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "kijani-{{ env }}"
        state: present

    - name: 2. Automatically generate Docker Hub Registry Credentials
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: kijani-registry-credentials
            namespace: "kijani-{{ env }}"
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: "{{ { 'auths': { 'https://index.docker.io/v1/': { 'username': docker_user, 'password': docker_password, 'email': docker_email, 'auth': (docker_user + ':' + docker_password) | b64encode } } } | to_json }}"

    - name: 3. Add Prometheus Helm repository
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"

    - name: 4. Install Prometheus 
      kubernetes.core.helm:
        name: prometheus
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: monitoring
        create_namespace: true
        wait: true
        timeout: "10m0s"
        values:
          grafana:
            enabled: false
          alertmanager:
            enabled: false
          nodeExporter:
            enabled: false
          defaultRules:
            create: false

    - name: 5. Apply Native Environment-Specific ConfigMap
      kubernetes.core.k8s:
        state: present
        namespace: "kijani-{{ env }}"
        template: "../k8s/manifests/kk-payments-configmap.yaml.j2"

    - name: 6. Apply Shared Application Layout
      kubernetes.core.k8s:
        state: present
        namespace: "kijani-{{ env }}"
        src: "{{ item }}"
      loop:
        - "../k8s/manifests/kk-payments-deployment.yaml" 
        - "../k8s/manifests/kk-payments-service.yaml"
        - "../k8s/manifests/kk-payments-alerts.yaml" 